name: Build

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Загрузка энвайрмента
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Проверка ошибок
      - name: Run code style check
        run: ./gradlew spotlessCheck

      # Сборка
      - name: Build
        run: ./gradlew build

      # Пробуем Docker BuildX
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

      ## Создание Артефактов
      # Артефакт: создание jar файла
      - name: Upload application
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: build/libs/*.jar

      # Артефакт: степень покрытия тестами
      - name: Upload JaCoCo report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html

      # Артефакт: отчет по тестам
      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: build/reports/tests


### Тестовый запуск контейнеров так же можно сделать, но пока не нужно ###
#      - name: Create CI env
#        run: |
#          echo "BOT_TOKEN=fake-token" > .env

#      - name: Start containers
#        run: docker compose up -d

#      - name: Wait
#        run: sleep 30

#      - name: Check application health
#        run: curl --fail http://localhost:8080/actuator/health

#      - name: Stop containers
#        if: always()
#        run: docker compose down